---
ID: "31bbbc4f-bea7-41d9-b59d-ff7d4f704b8e"
Parent: "1cbacbf2-e240-4602-bea4-80df19787d7c"
Template: "6ea02006-b973-4826-bdfc-c8122c7b865a"
Path: /sitecore/system/Settings/Analytics/Marketing Automation/Activity Types/Erase form submissions/Parameters
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{F9952D92-6CE6-43FF-A322-186650462DF6}"
Languages:
- Language: "nl-NL"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200106T095740Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
