---
ID: "0b53ecbb-14de-44a2-861b-5274dd431742"
Parent: "eedd833d-25cd-412a-91f9-c33bfe7d56d6"
Template: "6ea02006-b973-4826-bdfc-c8122c7b865a"
Path: /sitecore/system/Settings/Analytics/Marketing Automation/Activity Types/Anonymize contact/Parameters
DB: master
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{F9952D92-6CE6-43FF-A322-186650462DF6}"
Languages:
- Language: "nl-NL"
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200106T095740Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
